### ISSUE TITLE
rsync missing in ubuntu 18, required for zm-mailbox

### ISSUE THREAD

**Issue by nikokio** [Zimbra/zm-base-os#3]
Hello,

At least in the Dockerfile for Ubuntu 18, the command rsync is missing. It is required when building zm-mailbox (as per defined in instructions/FOSS_staging_list.pl in zm-build project).

Without rsync, the build fails with a "No such file or directory" when calling "rsync -az store-conf.conf <TARGET>"

**Comment by nikokio** [comment]
Hello,

Same issue on Ubuntu 20, still present on Ubuntu 18, nothing has changed since 2020... Hard to believe... :(

**Comment by alabruna** [comment]
You just have to install rsync in the container either by modifying the Dockerfile or inside the shell with sudo apt isntall rsync

**Comment by nikokio** [comment]
@alabruna Indeed, I compile Zimbra by installing rsync in the container for a while, and it works... I opened an issue not to get help, but to get it fixed for everyone...

**Comment by silentsakky** [comment]
Fixed in https://github.com/Zimbra/zm-base-os/pull/12
